services:
  ingot:
    image: ghcr.io/onelitefeathernet/ingot:1.0.0 # x-release-please-version
    #
    # To build from sources:
    #
    # build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xmx${MEMORY} ${JAVA_COMPOSE_OPTS}
      - INGOT_OPTS=--port ${PORT} ${INGOT_COMPOSE_OPTS}
    volumes:
      - ingot-data:/app/data
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
  ingot-data: {}
